#!/usr/bin/env bash
#display information about subdomains

get_domains() {

    if [ "$2" ]
    then
        source=$(dig "$2.$1" | grep -A1 'ANSWER SECTION:')
        record=$(echo $source | awk '{print $7}')
        ip=$(echo $source | awk '{print $8}')
        echo "The subdomain $2 is a $record record and points to $ip"
        return 0
    fi
}
if [ -z "$1" ]
then
    return 1
elif [ "$2" ]
then
    get_domains "$1" "$2"
else
    get_domains "$1" "web-01"
    get_domains "$1" "web-02"
    get_domains "$1" "lb-01"
    get_domains "$1" "www"
fi