#!/usr/bin/env bash
# Nginx server so that /redirect_me is redirecting to another page
# Update information
# Install nginx
# Nginx listen to port 80

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Holberton School" > /var/www/html/index.nginx-debian.html
sed -i "46i rewrite ^/redirect_me$ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default
/etc/init.d/nginx restart

