#!/usr/bin/env bash
#Configure Nginx so that its HTTP response contains a custom header
host_name=$(hostnamectl | grep "Static hostname:" | awk '{print $3}')
sed -i "46i         add_header X-Served-By $host_name;" /etc/nginx/sites-available/default
/etc/init.d/nginx restart
