#!/usr/bin/env bash
#Install and configure HAproxy load balancer
apt-get install software-properties-common -y
add-apt-repository ppa:vbernat/haproxy-1.8 -y
apt-get update -y
apt-get install haproxy=1.8.\* -y

echo -e "\nfrontend http\n\tbind *:80\n\tmode http\n\tdefault_backend web_servers\n" >> /etc/haproxy/haproxy.cfg
echo -e "\nbackend web_servers\n\tbalance roundrobin\n\tserver web-01 35.231.105.155:80 check\n\tserver web-02 34.75.216.134:80 check\n" >> /etc/haproxy/haproxy.cfg
/etc/init.d/haproxy restart