#!/usr/bin/env bash
#print a quote infinately
#make a new file storing his own PID
#use signal handler to get exit clean
#the correct way to leave is using SIGQUIT to quit the file an delete file


touch /var/run/holbertonscript.pid
echo $$ > /var/run/holbertonscript.pid

_term() 
{ 
	rm /var/run/holbertonscript.pid
	echo "I hate the kill command"
}
trap _term SIGTERM

_int() 
{ 
	echo "Y U no love me?!" 
}
trap _int SIGINT


_quit() 
{
	rm /var/run/holbertonscript.pid
	exit
}
trap _quit SIGQUIT

while true
do
	echo "To infinity and beyond"
	sleep 2

done




