#!/usr/bin/env bash
#install an apache server and start it

docker exec -i 14d802bba3fb apt-get -y update
docker exec -i 14d802bba3fb apt-get install -y apache2
docker exec -i 14d802bba3fb /etc/init.d/apache2 restart