#!/usr/bin/env bash
#nginx as root
pkill apache2
sed -i -E 's/listen(.*)80(.*);/listen\18080\2;/g' /etc/nginx/sites-available/default
chown nginx:nginx /etc/nginx/nginx.conf
chmod 700 /etc/nginx/nginx.conf
sudo -u nginx /etc/init.d/nginx start
